### ISSUE TITLE
setMaxSpeedX/Y does not apply to negative numbers

### ISSUE THREAD

**Issue by staudt** [diogoschneider/quick#50]
When you set setMaxSpeedX or Y for a gameobject, it will curretly only apply to speed values that are positive. It should also apply to the negative equivalent value, as setSpeedX/Y goes both ways.

**Comment by staudt** [comment]
I can't seem to be able to add a label (i.e. bug, enhancement) to this issue. Please check if it is possible to enable that for non-admins.

**Comment by diogoschneider** [comment]
It is really a bug. And I have just added you as a collaborator, it seems to be the only way to be able to set labels. Welcome to the project! 😄

**Comment by diogoschneider** [comment]
Fixed on #51
